name: 'Github Code Agent'
description: 'AI Agent that operates Codex or Claude Code on GitHub issues'
author: 'olemp'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  github-token:
    description: 'Specify the GitHub Token'
    required: true
  trigger-labels:
    description: 'Comma-separated list of labels that can trigger the AI agents'
    required: false
  event-path:
    description: 'Specify the path to the GitHub Event JSON file'
    default: ${{ github.event_path }}
    required: false
  timeout:
    description: 'Specify timeout duration (seconds)'
    default: '600'
    required: false

  anthropic-api-key:
    description: 'Specify the Anthropic API Key'
    required: false
  anthropic-base-url:
    description: 'Specify the Anthropic API base URL'
    required: false
  anthropic-model:
    description: 'Specify the Anthropic model to use'
    required: false
  anthropic-small-fast-model:
    description: 'Specify the Anthropic small and fast model to use'
    required: false
  claude-code-use-bedrock:
    description: 'Use AWS Bedrock for Claude Code (0 or 1)'
    required: false
  anthropic-bedrock-base-url:
    description: 'Specify the Anthropic Bedrock API base URL'
    required: false
  anthropic-include-directories:
    description: 'Comma-separated list of directories to include in the workspace'
    required: false
  anthropic-max-turns:
    description: 'Specify the maximum number of turns to allow'
    required: false

  aws-access-key-id:
    description: 'Specify the AWS Access Key ID for Bedrock'
    required: false
  aws-secret-access-key:
    description: 'Specify the AWS Secret Access Key for Bedrock'
    required: false
  aws-region:
    description: 'Specify the AWS region for Bedrock'
    required: false
  disable-prompt-caching:
    description: 'Disable prompt caching (0 or 1)'
    required: false

  openai-api-key:
    description: 'Specify the OpenAI API Key'
    required: false
  openai-base-url:
    description: 'Specify the OpenAI API base URL'
    required: false
  openai-model:
    description: 'Specify the OpenAI model to use'
    required: false

  exclude-patterns:
    description: 'Comma-separated list of patterns to exclude'
    required: false
  include-patterns:
    description: 'Comma-separated list of patterns to include'
    required: false

  disabled:
    description: 'Disable the action (0 or 1, true or false)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile.github_action_dockerhub'

