name: 'Github Code Agent'
description: 'AI Agent that operates Claude Code on GitHub'
author: 'potproject'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  # Required
  github-token:
    description: 'Specify the GitHub Token'
    required: true
  anthropic-api-key:
    description: 'Specify the Anthropic API Key'
    required: true
  event-path:
    description: 'Specify the path to the GitHub Event JSON file'
    default: ${{ github.event_path }}
    required: false
  timeout:
    description: 'Specify timeout duration (seconds)'
    default: '300'
    required: false

  # Optional
  anthropic-base-url:
    description: 'Specify the Anthropic API base URL. Will be overridden if a claude-code-proxy is used'
    required: false
  anthropic-model:
    description: 'Specify the Anthropic model to use'
    required: false
  anthropic-small-fast-model:
    description: 'Specify the Anthropic small and fast model to use'
    required: false
  
  # Optional: Use Bedrock
  claude-code-use-bedrock:
    description: 'Use AWS Bedrock for Claude Code (0 or 1)'
    required: false
  anthropic-bedrock-base-url:
    description: 'Specify the Anthropic Bedrock API base URL'
    required: false
  aws-access-key-id:
    description: 'Specify the AWS Access Key ID for Bedrock'
    required: false
  aws-secret-access-key:
    description: 'Specify the AWS Secret Access Key for Bedrock'
    required: false
  aws-region:
    description: 'Specify the AWS region for Bedrock'
    required: false
  disable-prompt-caching:
    description: 'Disable prompt caching (0 or 1)'
    required: false

  # Optional: Use Claude Code Proxy
  use-claude-code-proxy:
    description: 'Use Claude Code Proxy (0 or 1)'
    required: false
  proxy-openai-api-key:
    description: 'Specify the OpenAI API key for proxy'
    required: false
  proxy-gemini-api-key:
    description: 'Specify the Gemini API key for proxy'
    required: false
  proxy-preferred-provider:
    description: 'Specify the preferred provider for proxy(openai or google)'
    required: false
  proxy-big-model:
    description: 'Specify the big model for proxy'
    required: false
  proxy-small-model:
    description: 'Specify the small model for proxy'
    required: false
  
runs:
  using: 'docker'
  # image: 'Dockerfile.github_action_dockerhub'
  image: 'Dockerfile'
